# Generated by Django 5.2.5 on 2026-04-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'verbose_name_plural': 'Medicine Categories'},
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='booked', max_length=20),
        ),
    ]
