# Generated by Django 5.2.5 on 2026-04-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_labtest_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
